#!/usr/bin/env bash

# This script generates a Hyprland monitor and workspace configuration
# based on the connected displays.

# CONFIGURATION
# ---
# Set the number of workspaces you want per monitor.
WORKSPACES_PER_MONITOR=10
# Set the path for the generated config file.
CONFIG_FILE="$HOME/.config/hypr/custom/monitors.conf"
# ---

# Ensure jq is installed
if ! command -v jq &>/dev/null; then
  echo "Error: jq is not installed. Please install it to use this script."
  exit 1
fi

# Clear the existing config file
>"$CONFIG_FILE"

# Add a header to the generated file
echo "# AUTOGENERATED by generate-monitor-config.sh" >>"$CONFIG_FILE"
echo "# DO NOT EDIT THIS FILE DIRECTLY" >>"$CONFIG_FILE"
echo "" >>"$CONFIG_FILE"

# Get monitor information in JSON format and generate monitor lines
hyprctl -j monitors | jq -r '.[] | "monitor=\(.name),\(.width)x\(.height)@\(.refreshRate | floor),\(.x)x\(.y),1"' >>"$CONFIG_FILE"

echo "" >>"$CONFIG_FILE"

# Generate workspace assignments
WORKSPACE_OFFSET=0
MONITOR_NAMES=$(hyprctl -j monitors | jq -r '.[].name')

for MONITOR in $MONITOR_NAMES; do
  echo "# Workspaces for monitor $MONITOR" >>"$CONFIG_FILE"
  for i in $(seq 1 $WORKSPACES_PER_MONITOR); do
    WORKSPACE_NUM=$((WORKSPACE_OFFSET + i))

    # Make the first workspace on the first monitor the default
    if [ "$WORKSPACE_NUM" -eq 1 ]; then
      echo "workspace = $WORKSPACE_NUM, monitor:$MONITOR, default:true" >>"$CONFIG_FILE"
    else
      echo "workspace = $WORKSPACE_NUM, monitor:$MONITOR, default:true" >>"$CONFIG_FILE"
    fi
  done
  WORKSPACE_OFFSET=$((WORKSPACE_OFFSET + WORKSPACES_PER_MONITOR))
  echo "" >>"$CONFIG_FILE"
done

echo "Hyprland monitor config generated at $CONFIG_FILE"
